# Generated by Django 6.0.7 on 2026-07-14 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('relationship', models.CharField(blank=True, max_length=50)),
                ('allergies', models.CharField(blank=True, max_length=200)),
                ('about', models.TextField(blank=True)),
                ('circle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='senior', to='circles.carecircle')),
            ],
        ),
    ]
