# Generated by Django 6.0.7 on 2026-07-15 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0004_logentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='logged_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
