# Generated by Django 6.0.7 on 2026-07-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0007_medication_doselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='doselog',
            name='amount_given',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
