# Generated by Django 6.0.7 on 2026-07-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0008_doselog_amount_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('caregiver', 'Caregiver'), ('family', 'Family member')], default='family', max_length=20),
        ),
    ]
